 @extends('backend.layouts.app')

 @section('title', 'Application')

 @section('content')
     <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
         crossorigin="anonymous"></script>
     @if ($sanad->description == 'বাৎসরিক আয়ের সনদপত্র')
         @include('applications.batshorik')
     @elseif ($sanad->description == 'মাসিক আয়ের সনদ')
         @include('applications.monthly')
     @elseif ($sanad->description == 'মৃত্যু সনদ')
         @include('applications.dead')
     @elseif ($sanad->description == 'ভূমিহীন সনদ')
         @include('applications.bhumihin')
     @elseif ($sanad->description == 'জাতীয়তা সনদ')
         @include('applications.nationality')
     @elseif ($sanad->description == 'নাগরিক সনদ')
         @include('applications.nagorik')
     @elseif ($sanad->description == 'পুনঃবিবাহ না হওয়ার প্রত্যয়ন')
         @include('applications.punobibaho')
     @elseif ($sanad->description == 'অভিভাবকের অনুমতিপত্র')
         @include('applications.obivabok')
     @elseif ($sanad->description == 'মুক্তিযোদ্ধা প্রত্যয়ন')
         @include('applications.freedomfighter')
     @elseif ($sanad->description == 'বিবিধ সনদ')
         @include('applications.others')
     @elseif ($sanad->description == 'অবিবাহিত সনদ')
         @include('applications.obibahito')
     @elseif ($sanad->description == 'স্থায়ী বাসিন্দা সনদ')
         @include('applications.permanentResident')
     @elseif ($sanad->description == 'প্রত্যায়ন পত্র নাম')
         @include('applications.samename')
     @elseif ($sanad->description == 'চারিত্রিক সনদ')
         @include('applications.charitrik')
     @elseif ($sanad->description == 'উত্তরাধিকার সনদ')
         @include('applications.uttoradhikar')
     @elseif ($sanad->description == 'ওয়ারিশ সনদ')
         @include('applications.oarish')
     @elseif ($sanad->description == 'ট্রেড লাইসেন্স')
         @include('applications.tradelicense')
     @elseif ($sanad->description == 'জাতীয় পরিচয় তথ্য সংশোধন')
         @include('applications.voterinfoCorrection')
     @elseif ($sanad->description == 'ভোটার এলাকা স্থানান্তর প্রত্যয়ন')
         @include('applications.voterMigration')
     @elseif ($sanad->description == 'পারিবারিক সনদ')
         @include('applications.paribarik')
     @endif
 @endsection
